# Generated by Django 5.1.5 on 2025-01-31 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_alter_stockquote_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockquote",
            unique_together={("company", "time")},
        ),
    ]
