# Generated by Django 5.1.5 on 2025-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_alter_stockquote_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockquote",
            name="raw_timestamp",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
